"""add fields in user table

Revision ID: 2609f74d21a6
Revises: 8e7987ced99f
Create Date: 2024-03-14 05:41:36.583868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2609f74d21a6'
down_revision: Union[str, None] = '8e7987ced99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('predicted_age', mysql.INTEGER(display_width=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'predicted_age')
    # ### end Alembic commands ###
