"""add fields in user table

Revision ID: 2cfea71b7769
Revises: a0c0228fc163
Create Date: 2024-03-14 06:31:56.757772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfea71b7769'
down_revision: Union[str, None] = 'a0c0228fc163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('message', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('contact', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_mode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_mode')
    op.drop_column('orders', 'contact')
    op.drop_column('orders', 'message')
    # ### end Alembic commands ###
