"""add fields in user table

Revision ID: 8e7987ced99f
Revises: 34a5acab4ee6
Create Date: 2024-03-14 04:52:59.758988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e7987ced99f'
down_revision: Union[str, None] = '34a5acab4ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'drinks', ['drink_id'], ['id'])
    op.add_column('drinks', sa.Column('available_quantity', mysql.INTEGER(display_width=11), nullable=True))
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'drinks', ['drink_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('drinks', 'available_quantity')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
